name: "[CI] Polis"

on:
  push:
    branches:
      - master
      - "*-stable"
      - "update-*"
  pull_request:
    branches:
      - master
      - "*-stable"
      - "update-*"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      RUBYOPT: '-W:no-deprecated'
    services:
      postgres:
        image: postgres:12.17
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.1
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      env:
        RAILS_ENV: test
        DATABASE_USERNAME: postgres
        POLIS_SITE_ID: ${{ secrets.POLIS_SITE_ID }}
      run: |
        bundle exec rake test_app
        bundle exec rake spec
